name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  beta:
    name: Deploy to Beta
    runs-on: ubuntu-latest
    environment:
      name: beta
      url: https://beta.glitter-boys.com
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: earthly/actions-setup@v1.0.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: deploy
        run: earthly --secret FLY_API_TOKEN -P +deploy.backend --stage=beta
  prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs:
      - beta
    environment:
      name: prod
      url: https://prod.glitter-boys.com
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: earthly/actions-setup@v1.0.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: deploy
        run: earthly --secret FLY_API_TOKEN -P +deploy.backend --stage=prod
